config/routes.rb
Rails.application.routes.draw do

  root 'users#show'

  resources :registrations, only: [:create, :update]

  get  'sign_up', to: 'registrations#new',    as: 'sign_up'
  post 'sign_up', to: 'registrations#create', as: 'create_user'
  get  'edit',    to: 'registrations#edit',   as: 'edit_user'
  put  'edit',    to: 'registrations#update', as: 'update_user'

  get    'login',  to: 'sessions#new',     as: 'new_login'
  post   'login',  to: 'sessions#create',  as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get  'forgot', to: 'passwords#new',    as: 'new_forgot_password'
  post 'forgot', to: 'passwords#create', as: 'forgot_password'
  get  'reset',  to: 'passwords#edit',   as: 'reset_password'
  put  'reset',  to: 'passwords#update', as: 'update_password'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  DEFAULT_NAME_REGEXP = /\A([a-zA-Z0-9.!\#$%&'*+\/=?^_`{|}~-]+)/
  has_secure_password
  after_create :send_welcome_email
  before_create :set_default_name

  validates :name, length: {minimum: 5}, presence: true,
    if: Proc.new { |user| user.name != user.default_name },
    on: :update

  validates :email, presence: true,
    uniqueness: true,
    format: { with: URI::MailTo::EMAIL_REGEXP }

  validates :password, length: {minimum: 8},
    unless: Proc.new { |user| user.password.nil? }

  def self.authenticate(email, password)
    user = User.find_by(email: email)

    if user and user.authenticate(password)
      return user
    else
      sleep((100.0 + rand(500.0)) / 1000.0)
      return false
    end
  end

  def default_name
    self.email[DEFAULT_NAME_REGEXP]
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def reset_password_token_expired?
    self.reset_password_sent_at + 6.hours <= Time.now
  end

  def generate_reset_password_token
    self.reset_password_token = Digest::SHA1.hexdigest("#{self.email}#{Time.now.to_i}")
    self.reset_password_sent_at = Time.now()
    self.save
    return self.reset_password_token
  end

  private
    def set_default_name
      self.name = self.default_name
    end

    def send_welcome_email
      UserMailer.welcome(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :signed_in?

  private
    def authenticate_user!
      if !signed_in?
        flash.now.alert = ["You need to sign in or sign up before continuing."]
        flash.keep(:alert)
        redirect_to new_login_path and return
      end
    end

    def authenticated?
      if signed_in?
        flash.now.notice = ["You are already signed in."]
        redirect_to root_path
      end
    end

    def signed_in?
      session[:user_id].present?
    end

    def signed_in! user
      session[:user_id] = user.id
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :authenticated?
  before_action :verify_token, only: [:edit, :update]

  def edit
  end

  def update
    @user.assign_attributes(permit_params)

    if @user.save
      flash.now.notice = ["Your password was changed successfully."]
      flash.keep(:notice)
      redirect_to new_login_path and return
    else
      flash.now.alert = @user.errors.full_messages
      render "edit"
    end
  end

  def create
    @user = User.find_by(email: permit_params[:email])

    @user.send_password_reset_email if @user.present?

    flash.now.notice = ["You will receive an email with a link to reset your password."]
    flash.keep(:notice)
    redirect_to new_login_path
  end

  def new
  end

  private
    def permit_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    def verify_token
      @user = User.find_by(reset_password_token: params[:token])

      if @user.nil? or  @user.reset_password_token_expired?
        flash.now.alert = ["Reset password link expired."]
        flash.keep(:alert)
        redirect_to new_login_path and return
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :authenticated?, only: [:create]
  before_action :authenticate_user!, only: [:edit, :update]

  def edit
  end

  def update
    current_user.assign_attributes(permit_params)

    if current_user.save
      flash.now.notice = ["You updated your account successfully."]
      flash.keep(:notice)
      redirect_to root_path and return
    else
      flash.now.alert = current_user.errors.full_messages
      render "edit"
    end
  end

  def create
    @user = User.new(permit_params)

    if @user.save
      flash.now.notice = ["Welcome! You have signed up successfully."]
      flash.keep(:notice)
      signed_in! @user
      redirect_to root_path
    else
      flash.now.alert = @user.errors.full_messages
      render "new"
    end
  end

  def new
    @user = User.new
  end

  private
    def permit_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticated?, only: [:new, :create]
  before_action :authenticate_user!, only: [:destroy]

  def create
    if @user = User.authenticate(permit_params[:email], permit_params[:password])
      signed_in! @user
      flash.now.notice = ["Welcome #{@user.name}! Signed in successfully."]
      flash.keep(:notice)
      redirect_to root_path and return
    else
      flash.now.alert = ["Invalid email or password."]
      render "new"
    end
  end

  def new
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    flash.now.notice = ["Signed out successfully."]
    flash.keep(:notice)
    redirect_to new_login_path
  end

  private
    def permit_params
      params.require(:session).permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def this_title_is title
    provide(:title, "#{title} - YangHungTW")
  end
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alert.html.haml
.yh-alert
  - if flash.alert
    .alert.alert-dismissible.alert-danger
      %button{class: "close", type: "button", "data-dismiss" => "alert"}
        = icon("fas", "times")
      %strong= "Oops!"
      %ul
        - flash.alert.each do |message|
          %li= message

  - if flash.notice
    .alert.alert-dismissible.alert-success
      %button{class: "close", type: "button", "data-dismiss" => "alert"}
        = icon("fas", "times")
      %ul
        - flash.notice.each do |message|
          %li= message

app/views/layouts/_header.html.haml
%header.navbar.bg-dark
  .container
    = link_to root_path, class: "navbar-brand" do
      %p.yh-brand-text.yh-first-bigger= "YANG"
      %p.yh-brand-text.yh-first-bigger= "HUNG"
      %p.yh-brand-text.yh-brand-bigger= "TW"

    - if signed_in?
      %ul.nav.navbar-nav.ml-auto
        %li
          = link_to "Logout" , logout_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= yield :title
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/header"
    .container
      = yield

app/views/users/show.html.haml
- this_title_is "User Information"

.row.yh-container
  .col-12.col-sm-8.mr-sm-auto.ml-sm-auto
    = render "layouts/alert"

    .jumbotron
      %h1.yh-page-title Your Information

      .form-group.row.no-gutters.yh-form-group
        .col-sm-2.col-form-label= "E-mail"
        .col-sm-10.form-control-plaintext= current_user.email

      .form-group.row.no-gutters.yh-form-group
        .col-sm-2.col-form-label= "Name"
        .col-sm-10.form-control-plaintext= current_user.name

      = link_to "Edit", edit_user_path, class: "btn btn-primary"